# Imagen base oficial de Nginx
FROM nginx:latest

# Copiar el archivo HTML personalizado al directorio público de Nginx
COPY index.html /usr/share/nginx/html/

# Exponer el puerto por defecto de Nginx
EXPOSE 80